name: DockerBuild

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs: 
  docker:
    runs-on: ubuntu-latest
    steps: 
      - 
        name: "Checkout Git repository"
        uses: actions/checkout@v2
      - 
        name: "Set up Python"
        uses: actions/setup-python@v1
        with: 
          python-version: 3.8
      -
        name: "Install alembic"
        run: "pip install alembic"
      -
        name: "Install click"
        run: "pip install click"
      -
        name: "Install Flask"
        run: "pip install Flask"
      -
        name: "Install Flask-Migrate"
        run: "pip install Flask-Migrate"
      -
        name: "Install Flask-SQLAlchemy"
        run: "pip install Flask-SQLAlchemy"
      -
        name: "Install greenlet"
        run: "pip install greenlet"
      -
        name: "Install gunicorn"
        run: "pip install gunicorn"
      -
        name: "Install itsdangerous"
        run: "pip install itsdangerous"
      -
        name: "Install Jinja2"
        run: "pip install Jinja2"
      -
        name: "Install Mako"
        run: "pip install Mako"
      -
        name: "Install MarkupSafe"
        run: "pip install MarkupSafe"
      -
        name: "Install psycopg2-binary"
        run: "pip install psycopg2-binary"
      -
        name: "Install python-dateutil"
        run: "pip install python-dateutil"
      -
        name: "Install python-dotenv"
        run: "pip install python-dotenv"
      -
        name: "Install python-editor"
        run: "pip install python-editor"
      -
        name: "Install six"
        run: "pip install six"
      -
        name: "Install SQLAlchemy"
        run: "pip install SQLAlchemy"
      -
        name: "Install typing-extensions"
        run: "pip install typing-extensions"
      -
        name: "Install Werkzeug"
        run: "pip install Werkzeug"
      -
        name: "Install Zipp"
        run: "pip install zipp"
      -
        name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v1
      - 
        name: Build and push Docker images
        uses: docker/build-push-action@v2.6.1
        with:
          push: false